### ISSUE TITLE
左侧数据遍历之后，发现上下滚动没同步数据，会出现白板

### ISSUE THREAD

**Issue by lmuscle** [w1301625107/Vue-Gantt-chart#117]
![image](https://user-images.githubusercontent.com/96758322/207499959-050bf55b-977d-4e1c-9830-43e5e81335db.png)
上下滚动之后，左侧数据没同步，左侧数据的格式改了下，想按需展示所以是用数组来控制要展示的字段的，给加上了一个遍历。

**Comment by w1301625107** [comment]
是因为你改了数据结构，然后出了问题？

**Comment by lmuscle** [comment]
是的，把左侧的表头用数组遍历了一下，可以给个思路去优化这个空白问题嘛？

**Comment by w1301625107** [comment]
你遍历后数组长度有变化吗？这个按需展示的功能你可以搜索vue-virtualize或者react- virtualize

**Comment by lmuscle** [comment]
数组长度没有变化，打印能打印出滚动数据，但是发现鼠标向下滑动，左侧是上方出现空白，方向反了；左右两边的数据也不对准了。

**Comment by w1301625107** [comment]
你可以用sandbox之类的搞一个demo看看

**Comment by lmuscle** [comment]
换了一种方式解决了
