### ISSUE TITLE
timeline下面一行是天，上面一行是月份能处理吗？

### ISSUE THREAD

**Issue by ldfctx** [w1301625107/Vue-Gantt-chart#119]
您好，我想要下面一行显示天，上面一行显示月份，我现在是用自定义的时间轴，但是底部滚动条滚动的时候，超过一定范围上面的文字会消失，请问有其他的处理方式吗？
效果图是这样的：
![image](https://user-images.githubusercontent.com/47104630/233831503-d054182d-3592-4445-bb25-b3b33ce24b6d.png)

**Comment by w1301625107** [comment]
<template v-slot:timeline="{day , getTimeScales}">
    
    <TestTimeline :day="day"></TestTimeline>
</template>

**Comment by w1301625107** [comment]
```
<template v-slot:timeline="{day , getTimeScales}">
    <!-- 你的时间刻度组件 -->
    <TestTimeline :day="day"></TestTimeline>
</template>
```

**Comment by ldfctx** [comment]
嗯嗯 谢谢
