### ISSUE TITLE
想要隐藏左侧要怎么设置？

### ISSUE THREAD

**Issue by ldfctx** [w1301625107/Vue-Gantt-chart#120]
你好，我想要隐藏左侧的列表，现在我用css样式处理的，发现显示当前时间的markline定位不对，有解决方法吗？

**Comment by w1301625107** [comment]
使用titleWidth

https://github.com/w1301625107/Vue-Gantt-chart#:~:text=%E5%A4%B4%E7%9A%84%E9%AB%98%E5%BA%A6-,titleWidth,-%E2%9D%8C
