### ISSUE TITLE
请问 scale  能设置 年 月 季度的秒数吗？

### ISSUE THREAD

**Issue by liulu663125** [w1301625107/Vue-Gantt-chart#121]
现在设置季度秒数 scale：7689600  无效

**Comment by w1301625107** [comment]
支持的是分钟，不是秒数

**Comment by liulu663125** [comment]
能支持 按月 按季度  按年  scale 筛选吗？

**Comment by w1301625107** [comment]
筛选？不明白什么意思

**Comment by w1301625107** [comment]
https://github.com/w1301625107/Vue-Gantt-chart#timeline-%E6%97%B6%E9%97%B4%E8%BD%B4slot
