### ISSUE TITLE
滚动到最下面的时候，最后一行block内容只显示一半的问题

### ISSUE THREAD

**Issue by xyydd** [w1301625107/Vue-Gantt-chart#123]
老哥，你的demo里就存在这个问题，请一下怎么解决

**Comment by xyydd** [comment]
复现：需要mac，一下子滚动到底，windows不知道有没有这个问题

**Comment by w1301625107** [comment]
你用的是mac 吧？

**Comment by xyydd** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快查看。

**Comment by w1301625107** [comment]
如果是mac,有两种：1.设置 hideXScrollBar 和  hideYScrollBar
 2

**Comment by xyydd** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快查看。
