### ISSUE TITLE
最开始时间块被遮挡

### ISSUE THREAD

**Issue by HYliangkai** [w1301625107/Vue-Gantt-chart#124]
<img width="1491" alt="image" src="https://github.com/w1301625107/Vue-Gantt-chart/assets/56477361/9eafc5d1-568e-4daf-9ec8-9e2dd6205336">

无论怎么移动都是显示不到最开始时间块,被遮挡住了

**Comment by w1301625107** [comment]
因为最开始时间块超出了时间范围，所以被遮住了多余的部分。时间范围拉长一点就正常了
