### ISSUE TITLE
开始/结束时间会随着屏幕宽度变化问题

### ISSUE THREAD

**Issue by HYliangkai** [w1301625107/Vue-Gantt-chart#130]
如题,当我设置 开始-结束时间区间为一天时(譬如12-01 00:00:00 ~ 12-01 13:59:59 ).如果屏幕宽度不够或者刚好够,会精确显示开始-结束时间在title上:
<img width="1241" alt="image" src="https://github.com/w1301625107/Vue-Gantt-chart/assets/56477361/79dd4f03-ab9e-4a47-a5d5-ab9bd306a24d">
而当我将屏幕宽度拉,屏幕宽度超过一天显示范围时,此时会显示出12-02的数据以铺满宽度(此时我传给组件的开始/结束时间范围仍然是12-01 00:00:00 ~ 12-01 13:59:59 ):
<img width="1771" alt="image" src="https://github.com/w1301625107/Vue-Gantt-chart/assets/56477361/f7e03279-4f28-4080-a4e5-cea7690d303c">
请问一下我该如何避免这种时间超过设定预期的情况,即我传给组件的时间范围就是显示的时间范围,不做因宽度拉伸而自动填充多余的时间  
多谢🙏

**Comment by w1301625107** [comment]
设置timeRangeCorrection为false
https://github.com/w1301625107/Vue-Gantt-chart#:~:text=%E4%BD%BF%E7%94%A8%E8%A7%81%E8%AF%B4%E6%98%8E-,timeRangeCorrection,-%E2%9D%8C

**Comment by HYliangkai** [comment]
感谢感谢🙏,问题已解决
