### ISSUE TITLE
关于性能优化问题

### ISSUE THREAD

**Issue by HYliangkai** [w1301625107/Vue-Gantt-chart#131]
作者你好,我现在遇到了性能问题:由于渲染的数据条数太多(5w条)导致浏览器渲染十分卡顿.  
请问一下有没有一些性能优化的办法,能让我把这些数据渲染出来然后又不那么卡顿啊  ...

**Comment by HYliangkai** [comment]
多谢🙏了

**Comment by w1301625107** [comment]
如果数据不需要响应式，先给数据用object.freeze处理一下，避免vue的代理，会节约很多资源
