### ISSUE TITLE
通过轮询不断更新datas的值，网页内存一直飙升直到崩溃

### ISSUE THREAD

**Issue by hongliangsam** [w1301625107/Vue-Gantt-chart#132]
![image](https://github.com/w1301625107/Vue-Gantt-chart/assets/50320208/3790bee8-4972-4d06-8ed5-4a30ef7d5c42)
![image](https://github.com/w1301625107/Vue-Gantt-chart/assets/50320208/564e4123-36a3-460c-9616-1b97c83148b0)
如图所示，使用setInterval2秒一次轮询更新datas数组，网页内存一直飙升直到崩溃，请问有何解决办法，感谢您的回复！

**Comment by w1301625107** [comment]
你可以看看是不是哪里内存泄漏了
