### ISSUE TITLE
请问手机端不能用吗？

### ISSUE THREAD

**Issue by khongshao** [w1301625107/Vue-Gantt-chart#16]
在手机上滑动没有反映，安卓和ios都一样

**Comment by w1301625107** [comment]
目前是的，因为没有考虑移动设备上使用，没有对手机对touch事件做处理，后期应该会加上支持的。

**Comment by w1301625107** [comment]
已在1.5.0  版本支持

**Comment by khongshao** [comment]
牛逼~！

**Comment by sunliangjie** [comment]
请问下现在是怎么在移动端触摸滑动的？使用后只能通过滑动进度条来滚动，不能通过直接滑动内容来滚动。

**Comment by w1301625107** [comment]
我试了一下，在chrome 开发者工具手机模拟里按住拖动是可以的，iphone上也是可以
