### ISSUE TITLE
请问，mock模拟出的块级元素被左侧列表遮挡住了怎么解决

### ISSUE THREAD

**Issue by tj-pickpeiqi123** [w1301625107/Vue-Gantt-chart#18]
请问，mock模拟出的块级元素被左侧列表遮挡住了怎么解决

**Comment by w1301625107** [comment]
举个🌰，比如时间轴是9点-10点，需要渲染的块是8点到10点，这个时候8点到9点的部分就在时间轴显示范围之外了，如果需要看到时间轴范围之外的部分，就需要把时间轴拉长一点，比如调整到7点到11点，就可以完整的看到渲染的块了
