### ISSUE TITLE
请问可以固定第一行数据吗？

### ISSUE THREAD

**Issue by tj-pickpeiqi123** [w1301625107/Vue-Gantt-chart#19]
请问可以固定第一行数据吗？不随滚动条滚动

**Comment by w1301625107** [comment]
代码里不支持的，但是有一个变通的方法。你可以看demo，demo里是2个gantt图拼在一起的，你可以把固定的数据放在上一个gantt图里，滚动的数据放在下一个甘特图里，这样就可以变相支持固定多个数据

**Comment by tj-pickpeiqi123** [comment]
还有一个问题，我在你的代码上做了修改，点击当前行高亮，但是我一滑动竖向滚动条，高亮的行就随着滚动条滚动，请问，怎么解决呢？

**Comment by w1301625107** [comment]
没有理解你的意思，有图片解释一下吗

**Comment by tj-pickpeiqi123** [comment]
加QQ说吧，这个好像不能发图片，我的QQ274764301

**Comment by w1301625107** [comment]
加了？问题是解决了吗

**Comment by tj-pickpeiqi123** [comment]
还没解决，想和您在QQ上探讨一下，不知道您方便加好友不

**Comment by w1301625107** [comment]
em....我好友请求已经发了很久了

**Comment by tj-pickpeiqi123** [comment]
我这没收到好友请求，要不我加您吧

**Comment by w1301625107** [comment]
605477926
