### ISSUE TITLE
关于mac系统横向滚动条左滑触发mac的后退和前进的bug

### ISSUE THREAD

**Issue by Vicew** [w1301625107/Vue-Gantt-chart#22]
非常感谢大佬研发出这么优秀的轮子供我满足需求使用

在使用的过程中，从一个页面跳转不开新页面进入到有甘特图的页面时，左右滚动的时候会触发mac的浏览器前进后退事件

![嘻嘻](http://blog.panxiandiao.com//20191210182930.png)

当前我的解决方法是只要有甘特图的页面都让他打开新页面，**但是还有一种用户返回到甘特图页面的这种情况无法解决**

感谢！！

**Comment by w1301625107** [comment]
> 左右滚动的时候会触发mac的浏览器前进后退事件

https://jingyan.baidu.com/article/bad08e1ede062b09c8512103.html

你是说这个吗？鼠标拖动滚动条左右滑动应该是没有问题的，应该触摸板的左右快速滑动触发了浏览器的回退，这个恐怕是js无法处理的。

> 但是还有一种用户返回到甘特图页面的这种情况无法解决

这个我也没有太好的想法

**Comment by Vicew** [comment]
感谢大佬🙏滚动条左右滑动没问题。就是苹果用户体验不太好

**Comment by Vicew** [comment]
> > 左右滚动的时候会触发mac的浏览器前进后退事件
> 
> https://jingyan.baidu.com/article/bad08e1ede062b09c8512103.html
> 
> 你是说这个吗？鼠标拖动滚动条左右滑动应该是没有问题的，应该触摸板的左右快速滑动触发了浏览器的回退，这个恐怕是js无法处理的。
> 
> > 但是还有一种用户返回到甘特图页面的这种情况无法解决
> 
> 这个我也没有太好的想法

感谢大佬🙏滚动条左右滑动没问题。就是苹果用户体验不太好

**Comment by w1301625107** [comment]
😂那你们用户还是很rich啊，用mac，win10好像也是有这个问题的

或者说你可以添加对方向键的处理，用方向键替代左右滚动

或者说你可以搞一个预览窗，通过拖动预览窗来实现滚动

**Comment by Vicew** [comment]
感谢大佬

我好好研究一下

**Comment by Vicew** [comment]
大佬我又来了

![时间区间选择](http://blog.panxiandiao.com//20191212195506.png)

选择时间的时候出现没有直接渲染的情况

![没有渲染](http://blog.panxiandiao.com//20191212195559.png)

滑动之后才会渲染出来

![感谢](http://blog.panxiandiao.com//20191212195647.png)

🙏

**Comment by w1301625107** [comment]
> 大佬我又来了
> 
> ![时间区间选择](https://camo.githubusercontent.com/fb2fe4159cfd4df0674c9fa2ce0499d449eca9d8/687474703a2f2f626c6f672e70616e7869616e6469616f2e636f6d2f2f32303139313231323139353530362e706e67)
> 
> 选择时间的时候出现没有直接渲染的情况
> 
> ![没有渲染](https://camo.githubusercontent.com/e9b5553c0f3f54e478134b4f763947f73df5e3a7/687474703a2f2f626c6f672e70616e7869616e6469616f2e636f6d2f2f32303139313231323139353535392e706e67)
> 
> 滑动之后才会渲染出来
> 
> ![感谢](https://camo.githubusercontent.com/fdcf4e10d227dcbd4cdae3814168d7478ef26f71/687474703a2f2f626c6f672e70616e7869616e6469616f2e636f6d2f2f32303139313231323139353634372e706e67)
> 
> 🙏

已修复

**Comment by w1301625107** [comment]
> > > 左右滚动的时候会触发mac的浏览器前进后退事件
> > 
> > 
> > https://jingyan.baidu.com/article/bad08e1ede062b09c8512103.html
> > 你是说这个吗？鼠标拖动滚动条左右滑动应该是没有问题的，应该触摸板的左右快速滑动触发了浏览器的回退，这个恐怕是js无法处理的。
> > > 但是还有一种用户返回到甘特图页面的这种情况无法解决
> > 
> > 
> > 这个我也没有太好的想法
> 
> 感谢大佬🙏滚动条左右滑动没问题。就是苹果用户体验不太好

https://juejin.cn/post/6947858245356617764 可以看看这个方案

**Comment by Vicew** [comment]
> > > > 左右滚动的时候会触发mac的浏览器前进后退事件
> > > 
> > > 
> > > https://jingyan.baidu.com/article/bad08e1ede062b09c8512103.html
> > > 你是说这个吗？鼠标拖动滚动条左右滑动应该是没有问题的，应该触摸板的左右快速滑动触发了浏览器的回退，这个恐怕是js无法处理的。
> > > > 但是还有一种用户返回到甘特图页面的这种情况无法解决
> > > 
> > > 
> > > 这个我也没有太好的想法
> > 
> > 
> > 感谢大佬🙏滚动条左右滑动没问题。就是苹果用户体验不太好
> 
> https://juejin.cn/post/6947858245356617764 可以看看这个方案

可以解决！！Nice

**Comment by w1301625107** [comment]
> > > > > 左右滚动的时候会触发mac的浏览器前进后退事件
> > > > 
> > > > 
> > > > https://jingyan.baidu.com/article/bad08e1ede062b09c8512103.html
> > > > 你是说这个吗？鼠标拖动滚动条左右滑动应该是没有问题的，应该触摸板的左右快速滑动触发了浏览器的回退，这个恐怕是js无法处理的。
> > > > > 但是还有一种用户返回到甘特图页面的这种情况无法解决
> > > > 
> > > > 
> > > > 这个我也没有太好的想法
> > > 
> > > 
> > > 感谢大佬🙏滚动条左右滑动没问题。就是苹果用户体验不太好
> > 
> > 
> > https://juejin.cn/post/6947858245356617764 可以看看这个方案
> 
> 可以解决！！Nice

你是用哪一个方案？
