### ISSUE TITLE
如果屏幕足够长，时间条就会一直渲染下去

### ISSUE THREAD

**Issue by luyu1314** [w1301625107/Vue-Gantt-chart#23]
如果是在同一天， 这个问题就很明显 ，我设置的时间是8:00 - 14:00，  时间条会一直渲染下去时间填充完屏幕。

我缩放了一下demo：他也会一直渲染完屏幕
![image](https://user-images.githubusercontent.com/19934118/71440838-dd70d580-2739-11ea-9723-475a306cd23d.png)

**Comment by w1301625107** [comment]
功能是这样设计，因为以前觉得不填充不好看
最近在写一个版本有一个开关可以关闭这种行为，如果不急可以等更新。

**Comment by luyu1314** [comment]
> 功能是这样设计，因为以前觉得不填充不好看
> 最近在写一个版本有一个开关可以关闭这种行为，如果不急可以等更新。

我也在想，不填满也很奇怪。所以给他固定宽度了。

**Comment by luyu1314** [comment]
我还有个问题啊。
如果重新选了时间，请求了接口拿到了新的数据。页面不会重新渲染，需要拖一下，或者是动一下才会渲染出来。

这个我应该怎么解决呢？

**Comment by w1301625107** [comment]
demo里，更改了时间或者是行数和块数后，数据都是重新计算出来的，都是有触发重新渲染的。
所以，我觉得是你更新数据的方法有问题，没有让vue检测到。

**Comment by luyu1314** [comment]
因为我重新选了某天的日期后，时间还是8:00-14:00，时间条没变化， 行数和块数 都没变化。只有数据变了(⊙o⊙)…

**Comment by w1301625107** [comment]
日期，行数，块数 其中一个变了，数据都会变的

**Comment by w1301625107** [comment]
> > 功能是这样设计，因为以前觉得不填充不好看
> > 最近在写一个版本有一个开关可以关闭这种行为，如果不急可以等更新。
> 
> 我也在想，不填满也很奇怪。所以给他固定宽度了。

已更新1.4.0 ，新增开关 timeRangeCorrection，可关闭自动填充
