### ISSUE TITLE
可以搞这个吗》？

### ISSUE THREAD

**Issue by weituotian** [w1301625107/Vue-Gantt-chart#25]
![image](https://user-images.githubusercontent.com/7270968/74219765-b6219800-4ce8-11ea-9926-7c17265436a9.png)

日期下面可以标明是星期几

可以通过slot实现还是只能修改源码啊？》

**Comment by w1301625107** [comment]
你急用的话可以自己改造一下，改这个文件
[链接](https://github.com/w1301625107/Vue-Gantt-chart/blob/master/src/components/time-line/index.vue)

**Comment by weituotian** [comment]
@w1301625107 好的，我试试，thanks
