### ISSUE TITLE
需求：实际开始时间实际结束时间

### ISSUE THREAD

**Issue by andyz168** [w1301625107/Vue-Gantt-chart#26]
很赞的项目，有个需求是能显示实际开始时间和实际结束时间，深色显示，计划开始时间计划结束时间浅色显示，
![image](https://user-images.githubusercontent.com/22382971/76270051-ce1c1580-62ae-11ea-94cf-12817038ea34.png)
这个图片不是要翻墙吧。
在组件中blocks/index.vue，对应的数据也需要修改

**Comment by w1301625107** [comment]
没看懂你想要加什么？
 是要在条上显示几分几秒吗？那在slot里应该有你要的数据。

**Comment by andyz168** [comment]
> 没看懂你想要加什么？
> 是要在条上显示几分几秒吗？那在slot里应该有你要的数据。

比如线条是这样的：计划开始9点， 实际开始9点半；计划结束10点，实际结束10点半；当然实际情况也有提前开始，提前结束的。

**Comment by w1301625107** [comment]
那你实际显示一个条，计划显示一个条，两个条绝对定位叠一起有什么问题吗

**Comment by andyz168** [comment]
> 那你实际显示一个条，计划显示一个条，两个条绝对定位叠一起有什么问题吗

没问题，就这个意思，就是颜色区分出来，我懂你意思了。编号为123的 有2条数据一个是计划 ，一个是实际，然后颜色区分

**Comment by w1301625107** [comment]
嗯，那现在你是哪里遇到问题了吗

**Comment by andyz168** [comment]
> 嗯，那现在你是哪里遇到问题了吗

没有，其实这个算是一个条形里的属性；按你这个解决方案，需要做一个关联，编号一样，其他属性 id，计划时间，实际时间不一样。另外这样处理的话，重叠条形没问题，条形中的文字会不美观。

**Comment by w1301625107** [comment]
也可以两种条在一个框里，您可以在一个框里套另外一个框，因为有提供计算的方法，稍微计算下就可以得出位置。

至于文字不美观，你可以问问设计美术，看看有没有好的显示方法。

或者你可以做浮动显示，鼠标移动上去，让其index 高一点，避免因为盖住显示不全的问题，当鼠标移走就低回去。
