### ISSUE TITLE
需求：光明号分组

### ISSUE THREAD

**Issue by andyz168** [w1301625107/Vue-Gantt-chart#27]
可以按相同名称为光明号的分组
![Snipaste_2020-03-10_09-19-05](https://user-images.githubusercontent.com/22382971/76270475-5c44cb80-62b0-11ea-91f4-3d51df9a9896.png)

**Comment by w1301625107** [comment]
em 。
这个 东西急用的话，可以通过排序去分组，就是效果可能不好。
动态高度这个可能得等很久了。

**Comment by andyz168** [comment]
https://neuronet.io/gantt-elastic/#/
有这种，如果是分组的，先只计算父节点高度，点开然后重新计算。

**Comment by w1301625107** [comment]
可以通过排序先父子子父子按顺序排好，然后控制子级显示隐藏状态，默认显示父级。

点击对应父级后，把对应子级显示。

用平面去模拟树的多级结构。
