### ISSUE TITLE
虚拟dom能关闭，显示有问题

### ISSUE THREAD

**Issue by witsea** [w1301625107/Vue-Gantt-chart#30]
虚拟dom显示不正确，在可视范围内，dom时隐时现
![QQ截图20200328120410](https://user-images.githubusercontent.com/30461914/77814501-930e4480-70ec-11ea-9834-48ebb1d120a2.png)
![QQ截图20200328120442](https://user-images.githubusercontent.com/30461914/77814503-9d304300-70ec-11ea-8f3e-8f3c91d5b1d6.png)
![QQ截图20200328120543](https://user-images.githubusercontent.com/30461914/77814504-9dc8d980-70ec-11ea-9b40-d9f9bfed1ccd.png)

**Comment by w1301625107** [comment]
em,demo里完全没有问题，你最好检查一下你的数据。
这一张图我也看不出来什么问题，有代码吗，codesandbox 吗

**Comment by witsea** [comment]
`     <v-gantt-chart :scale="720"
                                       :end-time="statisticData.voyageScheduleEndTime"
                                       :datas="statisticData.voyageSchedule"
                                       :cell-height="40"
                                       :preload="0"
                                       class="self-chart">
                            <template slot="title">
                                <span></span>
                            </template>
                            <template v-slot:block="{item}">
                                <div v-if="true" :class="[item.status==1?'green':'orange']" style="border-radius: 5px" class="mt-2 px-2 white--text">

                                    {{item.name}}
                                </div>
                            </template>
                            <template v-slot:left="{data}">
                                <div class="px-4 py-2">{{data.id}}</div>
                            </template>
                        </v-gantt-chart>`

![QQ截图20200330163043](https://user-images.githubusercontent.com/30461914/77891823-25a51400-72a4-11ea-8d7b-448807d1112b.png)

**Comment by w1301625107** [comment]
可以把传给组件的数据给全吗，而且不要给图片，这样我很难帮你

**Comment by witsea** [comment]
一样的代码在codesandbox 没有这个问题？？
有关闭虚拟dom的配置吗？
谢谢

**Comment by witsea** [comment]
解决了，    <v-gantt-chart v-show=‘有数据以后再显示’；就不存在这个问题了

**Comment by w1301625107** [comment]
一脸茫然，问题解决就好。

**Comment by witsea** [comment]
谢谢了
