### ISSUE TITLE
有没有属性让时间线在打开页面时就显示，不一开始就显示之前的时间点

### ISSUE THREAD

**Issue by KlaywwW** [w1301625107/Vue-Gantt-chart#33]
![image](https://user-images.githubusercontent.com/56384695/85187306-3c6e6c00-b2d1-11ea-813a-443e4b1feceb.png)
![image](https://user-images.githubusercontent.com/56384695/85187312-4c864b80-b2d1-11ea-88ee-3886f9714be7.png)
谢谢！

**Comment by w1301625107** [comment]
你说的是红色的那个竖线吗？还是点击块后在块的前后出现的那个线吗？

**Comment by KlaywwW** [comment]
> 你说的是红色的那个竖线吗？还是点击块后在块的前后出现的那个线吗？

红色的当前时间线

**Comment by w1301625107** [comment]
> 不一开始就显示之前的时间点？

是什么意思？

红色显示的一直是当前时间。

**Comment by KlaywwW** [comment]
> > 不一开始就显示之前的时间点？
> 
> 是什么意思？
> 
> 红色显示的一直是当前时间。

**Comment by KlaywwW** [comment]
> > 不一开始就显示之前的时间点？
> 
> 是什么意思？
> 
> 红色显示的一直是当前时间。

我设定了18号到21号的时间段，现在一打开显示的是18号的，但是红色的当前时间在20号那个位置，我需要拖动才能看到，所以我想，直接看到当前时间的区间，拖动到前面再看18号的

**Comment by w1301625107** [comment]
奥，明白了。你需要默认显示当前时间范围的区间，对吧？

有一个 scrollToTime 字段， 你可以试试看，能不能满足你的要求。

**Comment by KlaywwW** [comment]
大佬，之前的问题已经搞定，现在怎么把项目打包成单页面应用？

**Comment by w1301625107** [comment]
em，通常是npm run build，百度一下答案很多，而且更详细

**Comment by KlaywwW** [comment]
> em，通常是npm run build，百度一下答案很多，而且更详细

已经解决了，去掉了就可以了
![image](https://user-images.githubusercontent.com/56384695/85246195-90698400-b47c-11ea-8dff-f839edbbb8ab.png)

**Comment by KlaywwW** [comment]
感谢大佬的开源项目
