### ISSUE TITLE
请问这个能否实现出图中效果？

### ISSUE THREAD

**Issue by NerdNingNuo** [w1301625107/Vue-Gantt-chart#34]
![scheduler](https://user-images.githubusercontent.com/48057896/86609601-b6e00100-bfde-11ea-901c-3f07a35ec621.png)
请问这个能否实现出上图效果？我想要将表格左边的一列进行合并做出一个类似与员工的周考勤图
且将表头时间轴进行隐藏，只保留日期轴

**Comment by NerdNingNuo** [comment]
且将表头时间轴进行隐藏，只保留日期轴

**Comment by w1301625107** [comment]
名字中间的空白行目前看是不能实现的，其他可以，但是要改源代码。

你图中的效果感觉不需要用这个组件来做，自己写一个可能更快。
