### ISSUE TITLE
可否实现甘特条拖动的效果

### ISSUE THREAD

**Issue by dqiang** [w1301625107/Vue-Gantt-chart#4]
可否实现甘特条拖动的效果

**Comment by w1301625107** [comment]
拖动效果你可以尝试用vue-dragable（好像是这个）去包裹你的自定义组件，但是可能需要自己实现拖动后的数据同步一致的问题

**Comment by dqiang** [comment]
vue-dragable 主要 列表拖动，我想实现可以甘特条可以横向拖动，纵向不同行拖动，横向拖动行内位置任意放置，有一个方案是用jquery-ui的drag，但是我不知道还有没有其他好的方法，大佬能给点建议嘛，谢谢啦~~

**Comment by w1301625107** [comment]
我也只是个刚入门的前端啦。之前我也是用的jquery-ui,目前我也不知道其他方法。要注意一点就是纵向不同行拖动，目的行不在可视范围内，因为虚拟列表的原因，你拖动的甘特条可能会不见了，你需要改一下源码
![image](https://user-images.githubusercontent.com/29950066/60480115-eddc5200-9cba-11e9-8161-47825ab0d466.png)

**Comment by w1301625107** [comment]
还有横向拖动同样也有这个问题，默认是显示可视时间轴部分的，这个你在slot里判断就可以了。

但是对于拖动这个需求，之前我们考虑后还是取消了，因为拖动不够精确，还有碰撞，覆盖等问题，有精度要求还是弹窗输入更精准的值更好

**Comment by dqiang** [comment]
嗯，拖动会有碰撞，即单行会出现甘特条并排显示，每一行高度要重新计算，且每个甘特条的top也要计算，左侧任务栏行高也是同步的。

**Comment by w1301625107** [comment]
我这个对动态对行高是不支持，因为甘特条都是绝对定位的，每个行高都是固定的，所以你需要考虑下

**Comment by dqiang** [comment]
嗯，我看你您的代码了，这块儿就是得要修改一下，我先尝试修改下。

**Comment by wenxiuwang** [comment]
拖动功能实现了吗

**Comment by L3gacy03** [comment]
我用的是原生JS实现了拖拽

**Comment by kekebanban** [comment]
@L3gacy03 可以交流一下吗
