### ISSUE TITLE
关于时间精度和导出的疑问

### ISSUE THREAD

**Issue by XuLongfei96** [w1301625107/Vue-Gantt-chart#40]
1.时间精度目前支持年月吗？是不是需要修改下源码
2.导出的功能后续考虑会添加吗？楼主有没有实现的思路？

**Comment by w1301625107** [comment]
第一点你可以试试，目前支持天的倍数，30天以上都没有问题，但是会出现11/02 然后12/01 这种情况。
这个组件可能不太合适年月，因为月份有30天，31天，这个月的单位没有办法很好的转化到秒，而组件是按秒来算宽度的，所以有冲突的。

第二点导出功能，我没明白导出什么？

**Comment by XuLongfei96** [comment]
谢谢楼主；导出是指的导出甘特图，以图片或者pdf的形式

**Comment by w1301625107** [comment]
这个最好用其他库去实现，这里不考虑实现

**Comment by XuLongfei96** [comment]
好的，谢谢
