### ISSUE TITLE
请问运行时报错data、item未定义，断点mouted的时候就有值了，但是渲染不上去是为什么呢

### ISSUE THREAD

**Issue by sophia66666** [w1301625107/Vue-Gantt-chart#41]

**Comment by w1301625107** [comment]
em..你给的这些信息太少我很难搬到你，可以在codesandbox 上搞一个在线demo吗

**Comment by sophia66666** [comment]
> em..你给的这些信息太少我很难搬到你，可以在codesandbox 上搞一个在线demo吗

哈哈哈我知道来，是因为vue版本太低了，博主我还有很多问题，（1）左侧栏挡住面板导致信息没有展示全（2）时间可以按天显示吗，不用精确到小时

**Comment by w1301625107** [comment]
1. 不是左侧栏面板挡住，是超出部分overflow:hidden了
2. 可以按天，scale 填1440就是一天了
