### ISSUE TITLE
时间的粒度能否为毫秒，我看当前展示的最少是 1 min 啊

### ISSUE THREAD

**Issue by lw33** [w1301625107/Vue-Gantt-chart#46]
有没有什么方式能够展示出毫秒级别的差别

**Comment by w1301625107** [comment]
我这里提供一个方向。
组件可以设置1分钟的刻度，你可以把1分钟的刻度变得特别大，然后去改造这1分钟刻度的样式，比如搞一个60*1000毫秒刻度的图片，这样就变相实现了毫秒的差别
