### ISSUE TITLE
怎么自定义标题呢,lineheight是写死的

### ISSUE THREAD

**Issue by gitgundam** [w1301625107/Vue-Gantt-chart#48]

**Comment by w1301625107** [comment]
你说的标题是 title 吗？
https://github.com/w1301625107/Vue-Gantt-chart#title-%E6%A0%87%E9%A2%98slot

**Comment by gitgundam** [comment]
感谢,请教一下,能否一行显示两条数据呢（比如gtArray就放两个时间段，然后这两段时间在同一个格子里上下存在），还有时间怎么改成按月显示啊．．大佬

**Comment by w1301625107** [comment]
时间按月的话，有提供slot，但是可能满足不了。可以看看这个[issue40](https://github.com/w1301625107/Vue-Gantt-chart/issues/40)
https://github.com/w1301625107/Vue-Gantt-chart#timeline-%E6%97%B6%E9%97%B4%E8%BD%B4slot

两行数据的话，也有slot,显示在上还是在下得看你怎么写了,可以看看这个[issue45](https://github.com/w1301625107/Vue-Gantt-chart/issues/45)
https://github.com/w1301625107/Vue-Gantt-chart#block-%E5%AE%B9%E5%99%A8%E5%9D%97slot-%E6%9C%89-__%E4%B8%A4%E7%A7%8D__-%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F
