### ISSUE TITLE
dynamic data update problem

### ISSUE THREAD

**Issue by MIcQo** [w1301625107/Vue-Gantt-chart#5]
Hello,
i have a problem with updating data,
after receive new data from API, chart doesn't update, but if i want try scroll (horizontal) then chart is updated. why? 
some chance to fix?
Thanks.

edit: 
 if i want try scroll (horizontal) **OR hover on any block** then chart is updated.

**Comment by w1301625107** [comment]
Hi,
> i have a problem with updating data,after receive new data from API, chart doesn't update

I think that your method of updating your data may not be detected by vue.

You may need this [https://vuejs.org/v2/guide/list.html#Array-Change-Detection](https://vuejs.org/v2/guide/list.html#Array-Change-Detection)

> but if i want try scroll (horizontal) then chart is updated. why?

gantt components rerender will be triggered  when you scroll.
