### ISSUE TITLE
上下拖动效果

### ISSUE THREAD

**Issue by tj-pickpeiqi123** [w1301625107/Vue-Gantt-chart#6]
请问博主，能否添加上下拖动效果呢？

**Comment by w1301625107** [comment]
拖动效果你可以尝试用vue-dragable（好像是这个）去包裹你的自定义组件，但是可能需要自己实现拖动后的数据同步一致的问题

**Comment by tj-pickpeiqi123** [comment]
vue-dragable只能在数据列表上拖动，甘特图之间的块有空隙，实现不了拖拽到空隙上，请问怎么解决？

**Comment by w1301625107** [comment]
你可以参考一下这个https://github.com/w1301625107/Vue-Gantt-chart/issues/4
