### ISSUE TITLE
滚动错位如何处理

### ISSUE THREAD

**Issue by bourbon08** [w1301625107/Vue-Gantt-chart#65]
如图
![image](https://user-images.githubusercontent.com/11896072/121108232-fa20a080-c83b-11eb-96cc-b2353172708f.png)

**Comment by w1301625107** [comment]
什么情况下出现的

**Comment by bourbon08** [comment]
估计是单独设置cellheight, 没有修改v-slot:left的高度导致的

**Comment by bourbon08** [comment]
估计是单独设置cellheight, 没有修改v-slot:left的高度导致的

**Comment by w1301625107** [comment]
demo 里设置cellheight 不是可以同步的么？你是改了代码？

**Comment by bourbon08** [comment]
代码我只改过一些gant-block的颜色样式 , 反正现在加个leftbar的高度就不错位了, 谢谢老哥及时回复

**Comment by xyydd** [comment]
@bourbon08 老哥，你是滚动的时候错位嘛，加leftbar高度是整个leftbar的高度，但是一个leftbar-item的高度

**Comment by xyydd** [comment]
> 代码我只改过一些gant-block的颜色样式 , 反正现在加个leftbar的高度就不错位了, 谢谢老哥及时回复

@bourbon08  老哥，你是滚动的时候错位嘛，加leftbar高度是整个leftbar的高度，但是一个leftbar-item的高度
