### ISSUE TITLE
timelines 可加传自定义的字段显示吗？

### ISSUE THREAD

**Issue by yuchiahui** [w1301625107/Vue-Gantt-chart#69]
你好，请问标记时间功能可以开放自定义内容吗？

例如下图效果，我想传入早中晚班的字段显示：

![image](https://user-images.githubusercontent.com/46482610/126119496-02470538-ece9-4c2c-8a39-db75ed645879.png)

如果可以的话就太感谢了

**Comment by w1301625107** [comment]
可以的，这个我挑个时间加上吧。

**Comment by yuchiahui** [comment]
好的，谢谢作者

**Comment by w1301625107** [comment]
可以了 https://github.com/w1301625107/Vue-Gantt-chart/commit/649fa398aeddb608ffdf3aafb0c9d19048a43d45

**Comment by yuchiahui** [comment]
嗨，谢谢你的协助，Vue-Gantt-chart 实在帮了我很多忙。
还有个小部份想请问， slot 的参数是不是漏了 color  这个 attribute？若没有处理也无妨，已经很好使。

slot
```
<template v-slot:markLine="{markLineTime, getPosition}">
    <!-- 你的时间标记线组件 -->
    <TestMarkline :markLineTime="markLineTime" :getPosition="getPosition"></TestMarkline>
</template>
```
<html>
<body>


props
timelines | ❌ | array | -- | 显示标记时间，有特殊格式 [{time:'2019-01-11 18:18:18',color:'#00000'}]
-- | -- | -- | -- | --



</body>
</html>

**Comment by w1301625107** [comment]
em,我改一下吧，我把字段统一下

**Comment by w1301625107** [comment]
可以了 https://github.com/w1301625107/Vue-Gantt-chart/commit/68477d19943d340cb20e713ff806fc1f7602517b

**Comment by yuchiahui** [comment]
没有疑问了，很棒的组件，谢谢你🤣
