### ISSUE TITLE
项目长度过长如果无法完整显示时，就会整个消失

### ISSUE THREAD

**Issue by christan0612** [w1301625107/Vue-Gantt-chart#7]
您好
感谢开发此工具
我昨天使用了这个工具
但是发现到当他单一项目长度超过时间区块的可视范围时
就会整条消失不见
也就是如果有一条项目他长度很长我滚到中间时
他就整条消失了
你如果调整 DEMO 页面 Scale 设 10分钟也可以看到这问题

**Comment by w1301625107** [comment]
你好，谢谢你发现这个问题。

这个问题目前已经在新版本1.3.5修复了，你更新一下就可以了。demo也同样正常了。
