### ISSUE TITLE
修改gantt-block-item style

### ISSUE THREAD

**Issue by COOlJJJ** [w1301625107/Vue-Gantt-chart#71]
![image](https://user-images.githubusercontent.com/32292341/127414401-b6015e89-8144-430e-8644-10a3534275a5.png)
想请问能否修改这个gantt-block-item的style样式 根据Item的属性进行判断,希望能得到回复 ,非常感谢!

**Comment by w1301625107** [comment]
可以的 参考这个https://github.com/w1301625107/Vue-Gantt-chart/blob/master/README.md#%EF%B8%8F-customgenerateblocks-%E4%B8%BA-true-%E7%9A%84%E6%83%85%E5%86%B5

**Comment by COOlJJJ** [comment]
非常感谢,可以了!
