### ISSUE TITLE
想请教下，我加了拖拽之后，项目要怎么打包才能在发布npm之后，能够被自己的项目使用呀

### ISSUE THREAD

**Issue by lmuscle** [w1301625107/Vue-Gantt-chart#83]

**Comment by w1301625107** [comment]
本地npm link就好，其他你可以百度下npm 怎么发布一个包

**Comment by lmuscle** [comment]
发布前需要重新build嘛，因为我看"main": "dist/v-gantt-chart.umd.min.js"，但是我npm run build时会报错，对”NODE_ENV=DEMO“这个设置不大理解

**Comment by w1301625107** [comment]
npm run libbuild

**Comment by lmuscle** [comment]
解决了！谢谢！

**Comment by lmuscle** [comment]
解决了！谢谢！
