### ISSUE TITLE
请教一下,案例中的自己的gantt条组件和行名称组件有模板吗

### ISSUE THREAD

**Issue by Tomcat-7** [w1301625107/Vue-Gantt-chart#85]
（被导师逼着做前端的小白真诚发问）

**Comment by w1301625107** [comment]
模版？指什么？

**Comment by Tomcat-7** [comment]
在模拟数据中，左侧的火车列表是写成逗号分隔的字符串，在split分隔展示，如果想要从后端获得数据也需要这样吗，还是可以获得一个数据List数组，得到每一个火车的信息展示，感谢您的回复。

**Comment by w1301625107** [comment]
split分隔展示是因为图方便，正常从后端获取数据是你说的 list 的方式

**Comment by Tomcat-7** [comment]
谢谢您的解答，耽误您的时间了，非常感谢。
