### ISSUE TITLE
请问甘特图的每一条怎么增加不同的颜色,现在默认显示出来都是灰色的

### ISSUE THREAD

**Issue by Tomcat-7** [w1301625107/Vue-Gantt-chart#98]

**Comment by w1301625107** [comment]
你说的是哪个一部分？

**Comment by Tomcat-7** [comment]
这部分,datas数据中的每一条信息分配颜色






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月11日(星期五) 中午12:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [w1301625107/Vue-Gantt-chart] 请问甘特图的每一条怎么增加不同的颜色,现在默认显示出来都是灰色的 (Issue #98)





 
你说的是哪个一部分？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by w1301625107** [comment]
https://github.com/w1301625107/Vue-Gantt-chart#template-code

在自己的Block组件里自定义style就好了

**Comment by Tomcat-7** [comment]
只找了修改字体颜色和图像边框的API   ┭┮﹏┭┮ 我是前端小菜鸡

**Comment by w1301625107** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/background

**Comment by Tomcat-7** [comment]
非常感谢 找到了  谢谢您的耐心解答
